// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using antecipacao_recebivel.Data;

#nullable disable

namespace antecipacao_recebivel.Migrations
{
    [DbContext(typeof(DbContextRecebivel))]
    [Migration("20250212083812_limiteAntecipacao")]
    partial class limiteAntecipacao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("antecipacao_recebivel.Models.Empresa", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("cnpj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("faturamento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ramo")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("antecipacao_recebivel.Models.LimiteAntecipacao", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<decimal>("faixaMax")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("faixaMin")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("porcentagem")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("LimiteAntecipacao", (string)null);
                });

            modelBuilder.Entity("antecipacao_recebivel.Models.NotasFiscais", b =>
                {
                    b.Property<int>("idnotafiscal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idnotafiscal"));

                    b.Property<DateTime>("datavencimento")
                        .HasColumnType("datetime2");

                    b.Property<int>("idempresa")
                        .HasColumnType("int");

                    b.Property<string>("numero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("idnotafiscal");

                    b.ToTable("NotasFiscais");
                });
#pragma warning restore 612, 618
        }
    }
}
